#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

exit_24x24 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9oMAg8EOFe6isQAAAX7"
    "SURBVEjHlZZ/bFXlGcc/77nn3Hvbe2m5pe2lMFmoGw3OFagrg43BcEu1oJNIZDFD7BJEHOmy"
    "YLKNIQumMXVmYQ5mYhjJqAZiExhZo2MYXSngBOJIzWgCwZa1ZW3p7Q/vvb33nHPPec+zP9oa"
    "Y5Rlzz/v88/7/X7fH8/zfRRfEO3AD2fyNyDhQtKH0gCUQEbB6FMwBvAKsOsLcBR3iHao8+EV"
    "D1ZZgFEURqMoOC55AYEeoLkZOgFeAn5+J4JZ1SehNgdtZfPLlt+z82mSDz0skfKkCikDcnn0"
    "WApn4Kb858J59c83T9N/a7g3Ak/ths5WYM+nMEOfBW+HR8UMddY175i/+u13SKx/ALNknhKl"
    "uHb+AiN9Nykpr8C0oqp8UTW1a9dQYuhEX9+/m9ZqPboXPngeOPtZghPT4JuAP2/8+2mqdv4M"
    "CCGui9I+b7a0EKqqwigr462WFupWrcLJpClksiwsT6ramq9wpbt74xodjO+Hy7O4xmxyEpZh"
    "Gqc2dp0htu4BEEEchyCTgakp3FSKrzc0UNvYiJfJoLNZJJtF53Kk83nCKswzWzZjhq1D+6Hx"
    "uVmC9pkkD0eXPbOd4rUNiAjiebgTE6QHBsC2sTwP0RqtNdEgQHI57NFR3NFRyOfJ5KaIugEb"
    "6pZJFg4vmME1Z+59WTxZtrzm94c+UZ4dGuLYpk3MXbKE+x9/HLNQQCmFAGHfxxkZ4fR776GU"
    "Yk08Tkk0yng+z4p4qXq/Yt6XBlLjm4GTJoAPh5c+ugFUGHEcxHF4u7mZHVeuELIs/tLYyJx4"
    "HAFEhKhSnD1xgq3d3Sig45FHuG9kBFMEJzvFN+5awI3U+OHX4KTxBiQ8WJm8r1bcg88Bine2"
    "b+f+l1/GLhQY7OykxDRRtg1KISJYvk9FcTEfHT+O6zhsaG/ng54ezLzN9fRtSktiApRdgUWG"
    "C0nLMomEwyp36AXctgOUL6+jZMkSiouK+Ki1le/u2oVh24hSSBBgeR4r6utJtbYS8n2IRFi6"
    "79eMjQwwMDSI4TiqyDTFhXJDQ6kRCaPyWXxgcN+vqFhZT0Fruvfs4d6GBvL9/ViFAgqm3yAI"
    "sFMpFldWcnHbNrTWzFu9mp6BYQKgkLeJhS0KUGxoUAEK7fmIQM6GaGUlgfbJnOsiHI0ijkuo"
    "4GFEIqhIhLDWKNvG1IJ94QKB1kQTcwHwBQLPR0TQgCmQdV0XHRjo2bILhEAgIsKtA78gdm89"
    "cQuuNf2YUCTCHBUw2nuV1PAAFnOmf55MF5UWUCKkPQ8DHFPB7bzn47meUFWtouk+5PYw+mtL"
    "WfjYFkafv4x9qYtAQeFfl9ABSATSaSi4UL1lI74IwVgKBZghC7SQ9jUGjBszLff64Ic9KnL3"
    "PYQikD91ilA0SvLZZzFi8wmMaWUSngYPAvAVxI0iql99FTFN7HffxTUhEYszmstTgHwxDBoA"
    "Aezo7nqf2OIatBFi8sgRjGvXmRweZum5c1gpE98DD/AEPA9KPoa6t04zkclQNDVF7969aAXJ"
    "aDGXJj8mBLsPgq8OAc1AK9xoeOh7dy8oi6nhMx2UlNZQdf0amfFxYiIUjh3D7jqPBJroN+sp"
    "erKJqaIi4okEqW99m/MX/8GXyxM4IK+lJsctSLZB8Enf/h2sPxAJy9DTP5Le79fJxRJk4Ks1"
    "krvaI6PZrAzlcjImImMiMmzbcjuTkfzNmzK0bp0cB/lrIi7dC+bLTwwlTbCt6dNG89uZ9QXY"
    "+VLYksEnNkvvhu/I2QqkGyT7g4fF7egQu79f7MFBcf92RnJPbJXLIH+ykLMVCflwYVJ+ahiy"
    "FV78XEd7EfglsB+arbB1cP3KFVKdnKdG+vuY6OuHCYfQTKHZgBM2iM8tpaqomFs5WzomJlUm"
    "kN8sgj1DIEc/zzJbgH3TJA9OwZHFFWULVyxeRGWsWLRjq0I+T+D5qEBAi6RyOXVpMs1V2x0L"
    "w+6j8PqTQNv/Mv29QAxIw2Mu/EFBZdQ0JR62CBDSrkdGa+VC2pg++B8D0G3/71QxM5KoG3CX"
    "C+UFKNbTNmgrmIjB4EHw77T/v22i7i7VWbvjAAAAAElFTkSuQmCC")
getexit_24x24Data = exit_24x24.GetData
getexit_24x24Image = exit_24x24.GetImage
getexit_24x24Bitmap = exit_24x24.GetBitmap

